services:
  backend1:
    image: simple-api:latest
    ports:
      - "8081:8080"
  backend2:
    image: simple-api:latest
    ports:
      - "8082:8080"
  backend3:
    image: simple-api:latest
    ports:
      - "8083:8080"
  backend4:
    image: simple-api:latest
    ports:
      - "8888:8080"
