server.tomcat.threads.min-spare: 2
simple-proxy:
  upstreams:
    - protocol: http
      host: localhost
      port: 8081
      health: /actuator/health
    - protocol: http
      host: localhost
      port: 8082
      health: /actuator/health
    - protocol: http
      host: localhost
      port: 8083
      health: /actuator/health
    - protocol: http
      host: localhost
      port: 8888
      health: /actuator/health
